services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dev:server"]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dev:worker"]
    volumes:
      - .:/app
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["dev:frontend"]
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: development
    restart: unless-stopped

volumes:
  redis-data:
